//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zelda.QuestCreator.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zelda.QuestCreator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string ButtonText_Cancel {
            get {
                return ResourceManager.GetString("ButtonText_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string ButtonText_OK {
            get {
                return ResourceManager.GetString("ButtonText_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the Quest Completion Event to add. ähnelt.
        /// </summary>
        public static string DialogTitle_CompletionEventSelection {
            get {
                return ResourceManager.GetString("DialogTitle_CompletionEventSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the Quest Goal to add. ähnelt.
        /// </summary>
        public static string DialogTitle_GoalSelection {
            get {
                return ResourceManager.GetString("DialogTitle_GoalSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the Quest to open. ähnelt.
        /// </summary>
        public static string DialogTitle_OpenQuest {
            get {
                return ResourceManager.GetString("DialogTitle_OpenQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the Quest Requirement to add. ähnelt.
        /// </summary>
        public static string DialogTitle_RequirementSelection {
            get {
                return ResourceManager.GetString("DialogTitle_RequirementSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the Quest Reward to add. ähnelt.
        /// </summary>
        public static string DialogTitle_RewardSelection {
            get {
                return ResourceManager.GetString("DialogTitle_RewardSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The name of the Quest must be set before it can be saved. ähnelt.
        /// </summary>
        public static string Error_QuestNameMustBeSetForSave {
            get {
                return ResourceManager.GetString("Error_QuestNameMustBeSetForSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quest Data Files (*.zq)|*.zq ähnelt.
        /// </summary>
        public static string Filter_QuestFiles {
            get {
                return ResourceManager.GetString("Filter_QuestFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quest &apos;{0}&apos; has been saved successfully. ähnelt.
        /// </summary>
        public static string Info_QuestXSavedSuccessfully {
            get {
                return ResourceManager.GetString("Info_QuestXSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quest Creator for TLoZ - Black Crown ähnelt.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The resource id that is used to receive the localized text
        ///that is shown when the quest has been completed.
        ///Should be in the format &apos;QC_X&apos;. ähnelt.
        /// </summary>
        public static string Tooltip_CompletedTextId {
            get {
                return ResourceManager.GetString("Tooltip_CompletedTextId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The location the quest must be delivered at.
        ///Interpreted differently regarding the set Deliver Type.
        ///
        ///        Instant: This field can be left empty.
        ///        NPC:     This field must contain the name that uniquely identifies the NPC.
        /// ähnelt.
        /// </summary>
        public static string Tooltip_DeliverLocation {
            get {
                return ResourceManager.GetString("Tooltip_DeliverLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die States how the player ends the quest. ähnelt.
        /// </summary>
        public static string Tooltip_DeliverType {
            get {
                return ResourceManager.GetString("Tooltip_DeliverType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The resource id that is used to receive the localized description of the quest.
        ///Should be in the format &apos;QD_X&apos;. ähnelt.
        /// </summary>
        public static string Tooltip_DescriptionId {
            get {
                return ResourceManager.GetString("Tooltip_DescriptionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die States whether the quest can be done over and over again.
        ///After completing a repeatable quest it becomes available to be picked-up again. ähnelt.
        /// </summary>
        public static string Tooltip_IsRepeatable {
            get {
                return ResourceManager.GetString("Tooltip_IsRepeatable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die States whether the quest&apos;s current state is hidden from the player. ähnelt.
        /// </summary>
        public static string Tooltip_IsStateHidden {
            get {
                return ResourceManager.GetString("Tooltip_IsStateHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The level of the quest. Quest difficulty can be induces by
        ///looking at the level of the quest compared to the level of the player. ähnelt.
        /// </summary>
        public static string Tooltip_Level {
            get {
                return ResourceManager.GetString("Tooltip_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The name that uniquely identifies the quest.
        ///Localization is done by looking up the resource string similiar to &apos;QN_X&apos;,
        ///where X is the name of the quest. ähnelt.
        /// </summary>
        public static string Tooltip_Name {
            get {
                return ResourceManager.GetString("Tooltip_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The resource id that is used to receive the localized text
        ///that is shown when the quest has not been completed yet.
        ///Should be in the format &apos;QNC_X&apos;. ähnelt.
        /// </summary>
        public static string Tooltip_NotCompletedTextId {
            get {
                return ResourceManager.GetString("Tooltip_NotCompletedTextId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The resource id that is used to receive the localized start text of the quest.
        ///Should be in the format &apos;QS_X&apos;. ähnelt.
        /// </summary>
        public static string Tooltip_StartTextId {
            get {
                return ResourceManager.GetString("Tooltip_StartTextId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The type of the quest. ähnelt.
        /// </summary>
        public static string Tooltip_Type {
            get {
                return ResourceManager.GetString("Tooltip_Type", resourceCulture);
            }
        }
    }
}
