//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zelda.NpcCreator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zelda.NpcCreator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonText_Cancel {
            get {
                return ResourceManager.GetString("ButtonText_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ButtonText_OK {
            get {
                return ResourceManager.GetString("ButtonText_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chance To Drop.
        /// </summary>
        public static string DataGridColumn_ChanceToDrop {
            get {
                return ResourceManager.GetString("DataGridColumn_ChanceToDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chance To Drop in %.
        /// </summary>
        public static string DataGridColumn_ChanceToDropInPercent {
            get {
                return ResourceManager.GetString("DataGridColumn_ChanceToDropInPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        public static string DataGridColumn_ItemName {
            get {
                return ResourceManager.GetString("DataGridColumn_ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MF Works.
        /// </summary>
        public static string DataGridColumn_MagicFindWorks {
            get {
                return ResourceManager.GetString("DataGridColumn_MagicFindWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Draw Strategy to use..
        /// </summary>
        public static string DialogTitle_DrawStrategySelection {
            get {
                return ResourceManager.GetString("DialogTitle_DrawStrategySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Entity Behaviour to use..
        /// </summary>
        public static string DialogTitle_EntityBehaviourSelection {
            get {
                return ResourceManager.GetString("DialogTitle_EntityBehaviourSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the NPC definition file to open..
        /// </summary>
        public static string DialogTitle_SelectNpcFile {
            get {
                return ResourceManager.GetString("DialogTitle_SelectNpcFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! The LootTable contains an invalid item &apos;{0}&apos;..
        /// </summary>
        public static string Error_TheLootTableContainsInvalidItemX {
            get {
                return ResourceManager.GetString("Error_TheLootTableContainsInvalidItemX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the NPC must be set..
        /// </summary>
        public static string Info_NameMustBeSet {
            get {
                return ResourceManager.GetString("Info_NameMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~ No Behaviour Set ~.
        /// </summary>
        public static string Info_NoBehaviourSet {
            get {
                return ResourceManager.GetString("Info_NoBehaviourSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All entities have been resaved..
        /// </summary>
        public static string Info_ResavedAllEntities {
            get {
                return ResourceManager.GetString("Info_ResavedAllEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving was successful..
        /// </summary>
        public static string Info_SaveSuccessful {
            get {
                return ResourceManager.GetString("Info_SaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuHeader_Exit {
            get {
                return ResourceManager.GetString("MenuHeader_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string MenuHeader_New {
            get {
                return ResourceManager.GetString("MenuHeader_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enemy.
        /// </summary>
        public static string MenuHeader_NewEnemy {
            get {
                return ResourceManager.GetString("MenuHeader_NewEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Merchant.
        /// </summary>
        public static string MenuHeader_NewMerchant {
            get {
                return ResourceManager.GetString("MenuHeader_NewMerchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Player Character (friendly).
        /// </summary>
        public static string MenuHeader_NewNpc {
            get {
                return ResourceManager.GetString("MenuHeader_NewNpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant.
        /// </summary>
        public static string MenuHeader_NewPlant {
            get {
                return ResourceManager.GetString("MenuHeader_NewPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string MenuHeader_Open {
            get {
                return ResourceManager.GetString("MenuHeader_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resave All.
        /// </summary>
        public static string MenuHeader_ResaveAll {
            get {
                return ResourceManager.GetString("MenuHeader_ResaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MenuHeader_Save {
            get {
                return ResourceManager.GetString("MenuHeader_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string MenuHeader_Tools {
            get {
                return ResourceManager.GetString("MenuHeader_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collision.
        /// </summary>
        public static string PropCate_Collision {
            get {
                return ResourceManager.GetString("PropCate_Collision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification.
        /// </summary>
        public static string PropCate_Identification {
            get {
                return ResourceManager.GetString("PropCate_Identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant.
        /// </summary>
        public static string PropCate_Merchant {
            get {
                return ResourceManager.GetString("PropCate_Merchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement.
        /// </summary>
        public static string PropCate_Movement {
            get {
                return ResourceManager.GetString("PropCate_Movement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quests.
        /// </summary>
        public static string PropCate_Quests {
            get {
                return ResourceManager.GetString("PropCate_Quests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string PropCate_Settings {
            get {
                return ResourceManager.GetString("PropCate_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string PropCate_Status {
            get {
                return ResourceManager.GetString("PropCate_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk.
        /// </summary>
        public static string PropCate_Talkable {
            get {
                return ResourceManager.GetString("PropCate_Talkable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vision.
        /// </summary>
        public static string PropCate_Vision {
            get {
                return ResourceManager.GetString("PropCate_Vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States how the Enemy behaves towards the Player..
        /// </summary>
        public static string PropDesc_AggressionType {
            get {
                return ResourceManager.GetString("PropDesc_AggressionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The base armor of the entity. Armor protects from physical damage..
        /// </summary>
        public static string PropDesc_Armor {
            get {
                return ResourceManager.GetString("PropDesc_Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mitigation the enemy has against physical attacks..
        /// </summary>
        public static string PropDesc_ArmorMitigation {
            get {
                return ResourceManager.GetString("PropDesc_ArmorMitigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States whether the Npc can be pushed around, by for example attacking..
        /// </summary>
        public static string PropDesc_CanBePushed {
            get {
                return ResourceManager.GetString("PropDesc_CanBePushed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States whether the Npc can change from one Floor to another..
        /// </summary>
        public static string PropDesc_CanChangeFloor {
            get {
                return ResourceManager.GetString("PropDesc_CanChangeFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States whether the entity can slide around the edges of a tile..
        /// </summary>
        public static string PropDesc_CanSlide {
            get {
                return ResourceManager.GetString("PropDesc_CanSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States whether the Npc can swim in deep water..
        /// </summary>
        public static string PropDesc_CanSwim {
            get {
                return ResourceManager.GetString("PropDesc_CanSwim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States whether the entity collides with the tile map..
        /// </summary>
        public static string PropDesc_CollidesWithMap {
            get {
                return ResourceManager.GetString("PropDesc_CollidesWithMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The offset from the position of the Npc to the start of the collision area..
        /// </summary>
        public static string PropDesc_CollisionOffset {
            get {
                return ResourceManager.GetString("PropDesc_CollisionOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of the collision area of the Npc..
        /// </summary>
        public static string PropDesc_CollisionSize {
            get {
                return ResourceManager.GetString("PropDesc_CollisionSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The color the cut animation of the Plant is tinted in..
        /// </summary>
        public static string PropDesc_CutEffectAnimationColor {
            get {
                return ResourceManager.GetString("PropDesc_CutEffectAnimationColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings of the IDrawDataAndStrategy..
        /// </summary>
        public static string PropDesc_DrawDataAndStrategySettings {
            get {
                return ResourceManager.GetString("PropDesc_DrawDataAndStrategySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The set IDrawDataAndStrategy defines how the Entity is drawn..
        /// </summary>
        public static string PropDesc_DrawDataAndStrategyType {
            get {
                return ResourceManager.GetString("PropDesc_DrawDataAndStrategyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The set IEntityBehaviour defines how the Entity is controlled..
        /// </summary>
        public static string PropDesc_EntityBehaviour {
            get {
                return ResourceManager.GetString("PropDesc_EntityBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings of the IEntityBehaviour..
        /// </summary>
        public static string PropDesc_EntityBehaviourSettings {
            get {
                return ResourceManager.GetString("PropDesc_EntityBehaviourSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of text from which the talkable entity chooses a line to speak from. (only considered if the player has exalted reputation towards the npc&apos;s faction).
        /// </summary>
        public static string PropDesc_ExaltedText {
            get {
                return ResourceManager.GetString("PropDesc_ExaltedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles the Exalted Text on/off..
        /// </summary>
        public static string PropDesc_ExaltedTextToggle {
            get {
                return ResourceManager.GetString("PropDesc_ExaltedTextToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The in-game faction the entity is part of..
        /// </summary>
        public static string PropDesc_Faction {
            get {
                return ResourceManager.GetString("PropDesc_Faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The range (in pixels) the Entity can feel other entities..
        /// </summary>
        public static string PropDesc_FeelingRange {
            get {
                return ResourceManager.GetString("PropDesc_FeelingRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States how the Entity is drawn relative to other Entities on the same Floor..
        /// </summary>
        public static string PropDesc_FloorRelativity {
            get {
                return ResourceManager.GetString("PropDesc_FloorRelativity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of text from which the talkable entity chooses a line to speak from. (only considered if the player has friendly or better reputation towards the npc&apos;s faction).
        /// </summary>
        public static string PropDesc_FriendlyText {
            get {
                return ResourceManager.GetString("PropDesc_FriendlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles the Friendly Text on/off..
        /// </summary>
        public static string PropDesc_FriendlyTextToggle {
            get {
                return ResourceManager.GetString("PropDesc_FriendlyTextToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of text from which the talkable entity chooses a line to speak from. (only considered if the player has hated or better reputation towards the npc&apos;s faction).
        /// </summary>
        public static string PropDesc_HatedText {
            get {
                return ResourceManager.GetString("PropDesc_HatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles the Hated Text on/off..
        /// </summary>
        public static string PropDesc_HatedTextToggle {
            get {
                return ResourceManager.GetString("PropDesc_HatedTextToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of text from which the talkable entity chooses a line to speak from. (only considered if the player has honored or better reputation towards the npc&apos;s faction).
        /// </summary>
        public static string PropDesc_HonoredText {
            get {
                return ResourceManager.GetString("PropDesc_HonoredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles the Honored Text on/off..
        /// </summary>
        public static string PropDesc_HonoredTextToggle {
            get {
                return ResourceManager.GetString("PropDesc_HonoredTextToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of text from which the talkable entity chooses a line to speak from. (only considered if the player has hostile or better reputation towards the npc&apos;s faction).
        /// </summary>
        public static string PropDesc_HostileText {
            get {
                return ResourceManager.GetString("PropDesc_HostileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles the Hostile Text on/off..
        /// </summary>
        public static string PropDesc_HostileTextToggle {
            get {
                return ResourceManager.GetString("PropDesc_HostileTextToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States whether the Npc collides with the Scene and other objects..
        /// </summary>
        public static string PropDesc_IsSolid {
            get {
                return ResourceManager.GetString("PropDesc_IsSolid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The localized name of the entity..
        /// </summary>
        public static string PropDesc_LocalizedName {
            get {
                return ResourceManager.GetString("PropDesc_LocalizedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The speed the Npc moves by default; without any modifications..
        /// </summary>
        public static string PropDesc_MovementSpeed {
            get {
                return ResourceManager.GetString("PropDesc_MovementSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unique name of the Npc. Npcs are saved under their name..
        /// </summary>
        public static string PropDesc_Name {
            get {
                return ResourceManager.GetString("PropDesc_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of text from which the talkable entity choses a line to speak from..
        /// </summary>
        public static string PropDesc_NeutralText {
            get {
                return ResourceManager.GetString("PropDesc_NeutralText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles the Neutral Text on/off..
        /// </summary>
        public static string PropDesc_NeutralTextToggle {
            get {
                return ResourceManager.GetString("PropDesc_NeutralTextToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the animation that is displayed once the Plant has been cut..
        /// </summary>
        public static string PropDesc_PlantCutEffectAnimationName {
            get {
                return ResourceManager.GetString("PropDesc_PlantCutEffectAnimationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value all pushing forces applied to this Entity are multiplied by..
        /// </summary>
        public static string PropDesc_PushingForceModifier {
            get {
                return ResourceManager.GetString("PropDesc_PushingForceModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The names that uniquely identify the quests this entity may give to the player..
        /// </summary>
        public static string PropDesc_QuestNames {
            get {
                return ResourceManager.GetString("PropDesc_QuestNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time in seconds it takes for the entity to respawn once killed..
        /// </summary>
        public static string PropDesc_RespawnTime {
            get {
                return ResourceManager.GetString("PropDesc_RespawnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of text from which the talkable entity chooses a line to speak from.(only considered if the player has revered or better reputation towards the npc&apos;s faction).
        /// </summary>
        public static string PropDesc_ReveredText {
            get {
                return ResourceManager.GetString("PropDesc_ReveredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles the Revered Text on/off..
        /// </summary>
        public static string PropDesc_ReveredTextToggle {
            get {
                return ResourceManager.GetString("PropDesc_ReveredTextToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of items sold by the Merchant..
        /// </summary>
        public static string PropDesc_SellList {
            get {
                return ResourceManager.GetString("PropDesc_SellList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of text from which the talkable entity chooses a line to speak from. (only considered if the player has unfriendly or better reputation towards the npc&apos;s faction).
        /// </summary>
        public static string PropDesc_UnfriendlyText {
            get {
                return ResourceManager.GetString("PropDesc_UnfriendlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles the Unfriendly Text on/off..
        /// </summary>
        public static string PropDesc_UnfriendlyTextToggle {
            get {
                return ResourceManager.GetString("PropDesc_UnfriendlyTextToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The range (in pixels) the Entity can see other entities..
        /// </summary>
        public static string PropDesc_VisionRange {
            get {
                return ResourceManager.GetString("PropDesc_VisionRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggression Type.
        /// </summary>
        public static string PropDisp_AggressionType {
            get {
                return ResourceManager.GetString("PropDisp_AggressionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor.
        /// </summary>
        public static string PropDisp_Armor {
            get {
                return ResourceManager.GetString("PropDisp_Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor Mitigation.
        /// </summary>
        public static string PropDisp_ArmorMitigation {
            get {
                return ResourceManager.GetString("PropDisp_ArmorMitigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Pushable.
        /// </summary>
        public static string PropDisp_CanBePushed {
            get {
                return ResourceManager.GetString("PropDisp_CanBePushed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can change Floor.
        /// </summary>
        public static string PropDisp_CanChangeFloor {
            get {
                return ResourceManager.GetString("PropDisp_CanChangeFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Slide.
        /// </summary>
        public static string PropDisp_CanSlide {
            get {
                return ResourceManager.GetString("PropDisp_CanSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Swim.
        /// </summary>
        public static string PropDisp_CanSwim {
            get {
                return ResourceManager.GetString("PropDisp_CanSwim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collides With Map.
        /// </summary>
        public static string PropDisp_CollidesWithMap {
            get {
                return ResourceManager.GetString("PropDisp_CollidesWithMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        public static string PropDisp_CollisionOffset {
            get {
                return ResourceManager.GetString("PropDisp_CollisionOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string PropDisp_CollisionSize {
            get {
                return ResourceManager.GetString("PropDisp_CollisionSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut Effect Animation Color.
        /// </summary>
        public static string PropDisp_CutEffectAnimationColor {
            get {
                return ResourceManager.GetString("PropDisp_CutEffectAnimationColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DrawDataAndStrategy Settings.
        /// </summary>
        public static string PropDisp_DrawDataAndStrategySettings {
            get {
                return ResourceManager.GetString("PropDisp_DrawDataAndStrategySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DrawDataAndStrategy.
        /// </summary>
        public static string PropDisp_DrawDataAndStrategyType {
            get {
                return ResourceManager.GetString("PropDisp_DrawDataAndStrategyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behaviour.
        /// </summary>
        public static string PropDisp_EntityBehaviour {
            get {
                return ResourceManager.GetString("PropDisp_EntityBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behaviour Settings.
        /// </summary>
        public static string PropDisp_EntityBehaviourSettings {
            get {
                return ResourceManager.GetString("PropDisp_EntityBehaviourSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exalted Text.
        /// </summary>
        public static string PropDisp_ExaltedText {
            get {
                return ResourceManager.GetString("PropDisp_ExaltedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exalted Text Toggle.
        /// </summary>
        public static string PropDisp_ExaltedTextToggle {
            get {
                return ResourceManager.GetString("PropDisp_ExaltedTextToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faction.
        /// </summary>
        public static string PropDisp_Faction {
            get {
                return ResourceManager.GetString("PropDisp_Faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeling Range.
        /// </summary>
        public static string PropDisp_FeelingRange {
            get {
                return ResourceManager.GetString("PropDisp_FeelingRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor Relativity.
        /// </summary>
        public static string PropDisp_FloorRelativity {
            get {
                return ResourceManager.GetString("PropDisp_FloorRelativity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly Text.
        /// </summary>
        public static string PropDisp_FriendlyText {
            get {
                return ResourceManager.GetString("PropDisp_FriendlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly Text Toggle.
        /// </summary>
        public static string PropDisp_FriendlyTextToggle {
            get {
                return ResourceManager.GetString("PropDisp_FriendlyTextToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hated Text.
        /// </summary>
        public static string PropDisp_HatedText {
            get {
                return ResourceManager.GetString("PropDisp_HatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hated Text Toggle.
        /// </summary>
        public static string PropDisp_HatedTextToggle {
            get {
                return ResourceManager.GetString("PropDisp_HatedTextToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honored Text.
        /// </summary>
        public static string PropDisp_HonoredText {
            get {
                return ResourceManager.GetString("PropDisp_HonoredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honored Text Toggle.
        /// </summary>
        public static string PropDisp_HonoredTextToggle {
            get {
                return ResourceManager.GetString("PropDisp_HonoredTextToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostile Text.
        /// </summary>
        public static string PropDisp_HostileText {
            get {
                return ResourceManager.GetString("PropDisp_HostileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostile Text Toggle.
        /// </summary>
        public static string PropDisp_HostileTextToggle {
            get {
                return ResourceManager.GetString("PropDisp_HostileTextToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Solid.
        /// </summary>
        public static string PropDisp_IsSolid {
            get {
                return ResourceManager.GetString("PropDisp_IsSolid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localized Name.
        /// </summary>
        public static string PropDisp_LocalizedName {
            get {
                return ResourceManager.GetString("PropDisp_LocalizedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement Speed.
        /// </summary>
        public static string PropDisp_MovementSpeed {
            get {
                return ResourceManager.GetString("PropDisp_MovementSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PropDisp_Name {
            get {
                return ResourceManager.GetString("PropDisp_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral Text.
        /// </summary>
        public static string PropDisp_NeutralText {
            get {
                return ResourceManager.GetString("PropDisp_NeutralText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral Text Toggle.
        /// </summary>
        public static string PropDisp_NeutralTextToggle {
            get {
                return ResourceManager.GetString("PropDisp_NeutralTextToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut Effect Animation Name.
        /// </summary>
        public static string PropDisp_PlantCutEffectAnimationName {
            get {
                return ResourceManager.GetString("PropDisp_PlantCutEffectAnimationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pushing-Force Modifier.
        /// </summary>
        public static string PropDisp_PushingForceModifier {
            get {
                return ResourceManager.GetString("PropDisp_PushingForceModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest Names.
        /// </summary>
        public static string PropDisp_QuestNames {
            get {
                return ResourceManager.GetString("PropDisp_QuestNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respawn Time.
        /// </summary>
        public static string PropDisp_RespawnTime {
            get {
                return ResourceManager.GetString("PropDisp_RespawnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revered Text.
        /// </summary>
        public static string PropDisp_ReveredText {
            get {
                return ResourceManager.GetString("PropDisp_ReveredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revered Text Toggle.
        /// </summary>
        public static string PropDisp_ReveredTextToggle {
            get {
                return ResourceManager.GetString("PropDisp_ReveredTextToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell List.
        /// </summary>
        public static string PropDisp_SellList {
            get {
                return ResourceManager.GetString("PropDisp_SellList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfriendly Text.
        /// </summary>
        public static string PropDisp_UnfriendlyText {
            get {
                return ResourceManager.GetString("PropDisp_UnfriendlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfriendly Text Toggle.
        /// </summary>
        public static string PropDisp_UnfriendlyTextToggle {
            get {
                return ResourceManager.GetString("PropDisp_UnfriendlyTextToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vision Range.
        /// </summary>
        public static string PropDisp_VisionRange {
            get {
                return ResourceManager.GetString("PropDisp_VisionRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Properties.
        /// </summary>
        public static string TabHeader_GeneralProperties {
            get {
                return ResourceManager.GetString("TabHeader_GeneralProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loot.
        /// </summary>
        public static string TabHeader_Loot {
            get {
                return ResourceManager.GetString("TabHeader_Loot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Npc Creator for TLoZ - Black Crown.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
